### PR TITLE
Deployed suggestions-tool to Heroku

### PR DESCRIPTION
**Pull request by mukulkhanna**
- Added support for matching issues (in the suggestions-tool) with categories of the index to show where the specific issue has been already covered.
- Ported from txt file to Postgres DB (running on Heroku) for storing issue-category pairs.
- Deployed app to Heroku

The app can be accessed here - https://gazebo-index.herokuapp.com

### CODE REVIEW

**Comment by mukulkhanna** [comment]
As of now, the code of this branch was manually pushed to Heroku, but once this PR is merged, we can integrate it with this repo.

**Comment by j-rivero** [comment]
> * Ported from txt file to Postgres (on Heorku) for storing issue-category pairs.

Question: which is the postrgre file containing the data?

**Comment by mukulkhanna** [comment]
There is no file for that. The data is stored on a Postgres DB server running on Heroku.

**Comment by mukulkhanna** [comment]
@j-rivero I think we can rename the Heroku app to `gazebo-doc-index` and also probably add `suggestion-tool` in some way. You can make the change from the Heroku dashboard.

**Pull request merged**
